### ISSUE TITLE
How can i use lora weight with this project ?

### ISSUE THREAD

**Issue by svjack** [junhahyung/STGuidance#2]
Hey, Thank you for provide this project, 
How can i load lora wight like https://huggingface.co/svjack/mochi_game_mix_early_lora do ? 🙂

**Comment by kinam0252** [comment]
Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right?
We're planning to integrate STG pipeline into diffusers soon, so once that's done, 
you can just use our pipeline to load LoRA with STG.😊

**Comment by svjack** [comment]
> Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊

Thank you

**Comment by svjack** [comment]
> Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊

Where can i start up by diffusers pipeline ?🙂

**Comment by kinam0252** [comment]
> > Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊
> 
> Where can i start up by diffusers pipeline ?🙂

It's not implemented yet, but I'll let you know once it's ready! If you'd like to try implementing it yourself, I recommend checking out the [PAG Diffusion Pipeline](https://huggingface.co/docs/diffusers/main/en/using-diffusers/pag) for reference.

**Comment by svjack** [comment]
> > > Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊
> > 
> > 
> > Where can i start up by diffusers pipeline ?🙂
> 
> It's not implemented yet, but I'll let you know once it's ready! If you'd like to try implementing it yourself, I recommend checking out the [PAG Diffusion Pipeline](https://huggingface.co/docs/diffusers/main/en/using-diffusers/pag) for reference.

Sure, I have try PAG in my fork version: https://github.com/svjack/Perturbed-Attention-Guidance. Awesome, thanks for bringing this feature to videos!

**Comment by kinam0252** [comment]
> > > > Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊
> > > 
> > > 
> > > Where can i start up by diffusers pipeline ?🙂
> > 
> > 
> > It's not implemented yet, but I'll let you know once it's ready! If you'd like to try implementing it yourself, I recommend checking out the [PAG Diffusion Pipeline](https://huggingface.co/docs/diffusers/main/en/using-diffusers/pag) for reference.
> 
> Sure, I have try PAG in my fork version: https://github.com/svjack/Perturbed-Attention-Guidance. Awesome, thanks for bringing this feature to videos!

Thanks for waiting! 🙌 We’ve implemented STG in the Mochi diffusers pipeline and updated it at [MochiSTGPipeline](https://github.com/junhahyung/STGuidance/tree/main/diffusers/mochi). Would you like to give it a try?

**Comment by svjack** [comment]
> > > > > Oh, you’re talking about using STG on the Mochi Diffusers pipeline, right? We're planning to integrate STG pipeline into diffusers soon, so once that's done, you can just use our pipeline to load LoRA with STG.😊
> > > > 
> > > > 
> > > > Where can i start up by diffusers pipeline ?🙂
> > > 
> > > 
> > > It's not implemented yet, but I'll let you know once it's ready! If you'd like to try implementing it yourself, I recommend checking out the [PAG Diffusion Pipeline](https://huggingface.co/docs/diffusers/main/en/using-diffusers/pag) for reference.
> > 
> > 
> > Sure, I have try PAG in my fork version: https://github.com/svjack/Perturbed-Attention-Guidance. Awesome, thanks for bringing this feature to videos!
> 
> Thanks for waiting! 🙌 We’ve implemented STG in the Mochi diffusers pipeline and updated it at [MochiSTGPipeline](https://github.com/junhahyung/STGuidance/tree/main/diffusers/mochi). Would you like to give it a try?

Thank you, i have try them in https://huggingface.co/svjack/mochi_game_landscape_early_lora and https://huggingface.co/svjack/mochi_game_mix_early_lora and have favourable output 😊
Thank you for your help.

**Comment by kinam0252** [comment]
Sounds Great! You're welcome :)
